### ISSUE TITLE
Invisible text

### ISSUE THREAD

**Issue by whatisjasongoldstein** [baukeposthuma/monolite#1]
Hi,

I'm using this theme, which is otherwise fantastic, and code-styled text inside settings or marketplace is either transparent or the same color as the background.

Here's a screenshot of the monolite extension page, where you can see the installation instruction has a bunch of invisible text.

![image](https://user-images.githubusercontent.com/377630/65103209-8ec5d980-d99b-11e9-915a-f863c21e2100.png)

Thanks!

**Comment by dotiful** [comment]
same issue for me.
@whatisjasongoldstein not sure if this is the right way, but as a workaround, you can fix it with this setting

```json
"workbench.colorCustomizations":
  "textPreformat.foreground": "#ebbf83"
}
```

**Comment by baukeposthuma** [comment]
Hi @whatisjasongoldstein,
I am so sorry for overlooking your comment. Glad you like the theme that really makes me happy! I have changed this in version 1.0.11 of the theme. Please let me know if this resolves your issue.
Thanks!
